import './globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from '../app/components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
      <html lang="en">
        <body className={`flex justify-center items-center min-h-screen w-full ${inter.className}`}>
          <div className="w-full max-w-lg mx-auto p-4 h-60">
            <Navbar/>

            <div className="text-left">
              {children}
            </div>
          </div>
        </body>
      </html>
  );
}
